pipeline:
  name: CDS-107471-qa
  identifier: CDS107471qa
  projectIdentifier: Keshav_Test_Project
  orgIdentifier: Keshav_Test_Org
  tags: {}
  stages:
    - stage:
        name: test
        identifier: test
        tags: {}
        template:
          templateRef: K8sRemoteTempqa
          versionLabel: v1
          gitBranch: main1
          templateInputs:
            type: Deployment
            spec:
              environment:
                environmentRef: <+input>
                environmentInputs: <+input>
                serviceOverrideInputs: <+input>
                infrastructureDefinitions: <+input>
              service:
                serviceRef: <+input>
                serviceInputs: <+input>
